# Generated by Django 3.1.6 on 2021-04-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('cidade', models.CharField(max_length=14)),
                ('senha', models.CharField(max_length=8)),
            ],
        ),
    ]
